FROM oven/bun AS build

WORKDIR /app

# Cache packages installation
COPY package.json bun.lock ./

RUN bun install --production --frozen-lockfile

COPY . .

ENV NODE_ENV=production

RUN bun build \
	--compile \
	--minify-whitespace \
	--minify-syntax \
	--target bun \
	--outfile server \
	src/index.ts

FROM gcr.io/distroless/base

WORKDIR /app

COPY --from=build /app/server server
COPY --from=build /app/node_modules node_modules

ENV NODE_ENV=production

CMD ["./server"]

ENV HOSTNAME=0.0.0.0
ENV PORT=3000

EXPOSE ${PORT}
